import { DatabaseSchema } from '../types';
import { INITIAL_DRIVER_PROFILE, INITIAL_HOMEPAGE_SETTINGS, INITIAL_SEO_SETTINGS, INITIAL_SITE_SETTINGS } from './data';
import { supabase } from './supabase';

export interface DbStatus { success: boolean; status: string; storageType: string; lastUpdated: string; counts: Record<string, number>; }
const tables: Record<string, string> = { whyChooseUs:'why_choose_us_benefits',services:'services',tours:'tours',destinations:'destinations',reviews:'reviews',faqs:'faqs',vehicles:'vehicles',routes:'routes',airports:'airports',mediaItems:'media_files',bookings:'bookings',messages:'contact_messages' };
const cols: Record<string,string[]> = { whyChooseUs:['title','description','icon','badge','display_order','is_active'],services:['name','slug','short_description','description','icon','featured_image','featured_image_data','featured_image_mime','starting_price','currency','features','is_active','sort_order'],tours:['title','slug','short_description','description','duration','starting_price','currency','pickup_location','highlights','itinerary','included','excluded','featured_image','featured_image_data','featured_image_mime','vehicle_type','is_active','sort_order'],destinations:['name','slug','short_description','description','things_to_do','travel_tips','featured_image','featured_image_data','featured_image_mime','is_active','sort_order'],reviews:['customer_name','country','rating','review','image_url','trip_type','source','is_published'],faqs:['question','answer','category','sort_order','is_published'],vehicles:['name','category','models','capacity_passengers','capacity_luggage','price_from','currency','features','image_url','image_data','image_mime','is_active','sort_order'],routes:['slug','origin','destination','route_name','estimated_duration','distance_km','sedan_price','suv_price','van_price','currency','is_popular','is_airport','airport_code','description','image_url','image_data','image_mime','is_published','sort_order'],airports:['code','name','city','province','pickup_instructions','image_url','image_data','image_mime','is_active','sort_order'],mediaItems:['title','url','category'],bookings:['customer_name','email','phone','whatsapp','service_id','route_id','tour_id','service_name','tour_title','pickup_location','destination','travel_date','pickup_time','passengers','luggage','vehicle_type','flight_number','hotel_name','special_requests','estimated_price','currency','status','assigned_driver','admin_notes'],messages:['name','email','phone','subject','message','status'] };
const db=()=>{if(!supabase)throw new Error('Supabase is not configured.');return supabase;};
const pick=(x:Record<string,unknown>, keys:string[])=>Object.fromEntries(Object.entries(x).filter(([k,v])=>keys.includes(k)&&v!==undefined));
const table=(name:string)=>{if(!tables[name])throw new Error(`Unknown collection: ${name}`);return tables[name];};
let lastWriteError = '';
const writeErrorMessage = (error: unknown) => {
  if (error instanceof Error) return error.message;
  if (error && typeof error === 'object' && 'message' in error) {
    const detail = error as { code?: string; message?: unknown };
    return `${detail.code ? `[${detail.code}] ` : ''}${String(detail.message)}`;
  }
  return String(error);
};

export const api = {
 async getFullDatabase(includeAdminData=false):Promise<DatabaseSchema|null>{try{const c=db();const entries=Object.entries(tables).filter(([n])=>includeAdminData||!['bookings','messages'].includes(n));const [site,hero,sections,driver,seo,...items]=await Promise.all([c.from('site_settings').select('*').limit(1).maybeSingle(),c.from('homepage_hero').select('*').limit(1).maybeSingle(),c.from('homepage_sections').select('*').order('display_order'),c.from('driver_profiles').select('*').eq('is_active',true).limit(1).maybeSingle(),c.from('seo_settings').select('*').limit(1).maybeSingle(),...entries.map(([,t])=>c.from(t).select('*'))]);const error=[site,hero,sections,driver,seo,...items].find(x=>x.error)?.error;if(error)throw error;const r:Record<string,unknown>={siteSettings:{...INITIAL_SITE_SETTINGS,...(site.data||{})},homepageSettings:{...INITIAL_HOMEPAGE_SETTINGS,hero:{...INITIAL_HOMEPAGE_SETTINGS.hero,...(hero.data||{})},sections:sections.data||[]},driverProfile:{...INITIAL_DRIVER_PROFILE,...(driver.data||{})},seoSettings:{...INITIAL_SEO_SETTINGS,...(seo.data||{})}};entries.forEach(([n],i)=>r[n]=items[i].data||[]);return r as unknown as DatabaseSchema;}catch(e){console.warn('Supabase content fetch failed:',e);return null;}},
 async getStatus():Promise<DbStatus|null>{try{const {error}=await db().from('services').select('id').limit(1);if(error)throw error;return{success:true,status:'connected',storageType:'supabase',lastUpdated:new Date().toISOString(),counts:{}};}catch{return null;}},
 async resetDatabase(){return null;},
 getLastWriteError(){return lastWriteError;},
 async insertItem<T extends {id?:string}>(collection:string,item:T):Promise<T|null>{lastWriteError='';try{const {data,error}=await db().from(table(collection)).insert(pick(item as Record<string,unknown>,cols[collection])).select().single();if(error)throw error;return data as T;}catch(e){lastWriteError=writeErrorMessage(e);console.warn(e);return null;}},
 async updateItem<T>(collection:string,id:string,updates:Partial<T>){lastWriteError='';try{const {error}=await db().from(table(collection)).update(pick(updates as Record<string,unknown>,cols[collection])).eq('id',id);if(error)throw error;return true;}catch(e){lastWriteError=writeErrorMessage(e);console.warn(e);return false;}},
 async deleteItem(collection:string,id:string){lastWriteError='';try{const {error}=await db().from(table(collection)).delete().eq('id',id);if(error)throw error;return true;}catch(e){lastWriteError=writeErrorMessage(e);console.warn(e);return false;}},
 async setCollection<T>(collection:string,items:T[]){return (await Promise.all(items.map(i=>this.updateItem(collection,(i as {id:string}).id,i)))).every(Boolean);},
 async updateSingleton<T>(name:'siteSettings'|'homepageSettings'|'driverProfile'|'seoSettings', updates:Partial<T>){try{const c=db();if(name==='homepageSettings'){const hero=pick(((updates as Record<string,unknown>).hero||{}) as Record<string,unknown>,['badge','title','subtitle','background_image','primary_btn_text','whatsapp_btn_text']);const {error}=await c.from('homepage_hero').update(hero).not('id','is',null);if(error)throw error;return true;}const [t,k]=name==='siteSettings'?['site_settings',['business_name','driver_name','tagline','description','phone','whatsapp','telegram','email','address','working_hours','primary_color','booking_form_settings','facebook_url','facebook_urls','instagram_url','tiktok_url','telegram_url','youtube_url','google_maps_url','google_business_url','tripadvisor_url']]:name==='driverProfile'?['driver_profiles',['driver_name','title','greeting','years_experience','languages','license_info','profile_photo_url','phone','whatsapp','rating','trips_completed','qualifications','why_choose_driver','is_active']]:['seo_settings',['meta_title','meta_description','keywords']];const {error}=await c.from(t).update(pick(updates as Record<string,unknown>,k)).not('id','is',null);if(error)throw error;return true;}catch(e){console.warn(e);return false;}},
 async getEmailStatus(){try{const {data}=await db().auth.getSession();const r=await fetch('/api/email/status',{headers:data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}});const text=await r.text();const body=JSON.parse(text);return r.ok?body:null;}catch{return null;}},
 async sendEmailTest(targetEmail:string){const {data}=await db().auth.getSession();const r=await fetch('/api/email/test',{method:'POST',headers:{'Content-Type':'application/json',...(data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{})},body:JSON.stringify({targetEmail})});const text=await r.text();try{return JSON.parse(text);}catch{return{success:false,error:`Email service returned HTTP ${r.status}.`,details:text.slice(0,240),hint:'Open Vercel Function logs for /api/email/test and verify Production environment variables.'};}}
};
